# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20171127_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Applicant')),
            ],
        ),
    ]
