# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_uploadfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='student',
        ),
        migrations.AddField(
            model_name='applicant',
            name='student',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
