# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20171127_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='lname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='uniname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
