# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-30 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20171128_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
