# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-30 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20171130_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='student',
        ),
    ]
