# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-30 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_remove_applicant_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
