# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20171130_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='contactnumber',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='languagesknow',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
