# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-02 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20171201_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='languagesknow',
            field=models.TextField(null=True),
        ),
    ]
