# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_like', models.ManyToManyField(blank=True, related_name='images_liked', to='prtest.School')),
            ],
        ),
    ]
