# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prtest', '0002_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.ManyToManyField(to='prtest.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='new',
            name='users_like',
        ),
        migrations.DeleteModel(
            name='New',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.AddField(
            model_name='course',
            name='courses',
            field=models.ManyToManyField(to='prtest.Teacher'),
        ),
    ]
