# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prtest', '0003_auto_20171025_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_by_teacher',
            field=models.ManyToManyField(to='prtest.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='students_by_course',
            field=models.ManyToManyField(to='prtest.Course'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='courses',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='student',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='students',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teachers',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
