# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prtest', '0011_auto_20171026_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_by_course',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_by_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prtest.Course'),
        ),
    ]
