# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 04:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0002_auto_20171128_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='position',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
