# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 04:59
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0003_auto_20171128_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
