# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 09:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0004_auto_20171128_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='longitude/latitude'),
        ),
    ]
